timeout: 30000
enableInlineShortcodes: false

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: false
    simple: false

  twitter:
    disabled: false
    enableDNT: false
    simple: false
    disableInlineCSS: false

  instagram:
    disabled: false
    simple: false

  youtube:
    disabled: false
    privacyEnhanced: false
