baseURL: "https://rajdeepgogoi.github.io/"
title: Rajdeep's Blogs 💻
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: true
buildExpired: false
enableEmoji: true

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main: 
                - identifer: archives
                  name: Archive
                  url: archives/
                  weight: 5
                - identifer: search
                  name: Search
                  url: search/
                  weight: 10
                - identifer: tags
                  name: Tags
                  url: tags/
                  weight: 10
                - identifer: about
                  name: About
                  url: about/
                  weight: 10
                

    
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    
    env: production
    author: Rajdeep
    defaultTheme: auto 
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    ShowShareButtons: true

    ShowReadingTime: true

    ShowPostNavLinks: true

    ShowCodeCopyButtons: true
    comments: true

    homeInfoParams:
        Title: "Hi! I am Rajdeep"
        Content: 
            Welcome to my website.

            - I like writing blogs. 

            - Check out my blogs 📚.


    socialIcons:
        - name: github
          url: "https://github.com/rajdeepgogoi"
       

   
    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
     highlight:
         # anchorLineNos: true
         codeFences: true
         guessSyntax: true
         lineNos: true
         # noClasses: false
         style: monokai


